# Generated by Django 3.1.1 on 2021-02-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=216)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='current_amount',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Offline Event', 'Offline Event'), ('Online_Event', 'Online_Event'), ('Fund_Raising_Event', 'Fund_Raising_Event')], default='Offline Event', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_amount',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='users/%y.%m/'),
        ),
        migrations.DeleteModel(
            name='Participate',
        ),
    ]
